### ISSUE TITLE
Merge Conflict

### ISSUE THREAD

**Issue by Saugat-bit** [BigyanParajuli/YETIWEARS_TEAM-E#17]
Git conflict while merging the code.

**Comment by BigyanParajuli** [comment]
Now the merge conflicts is resolved.
![image](https://github.com/BigyanParajuli/YETIWEARS_TEAM-E/assets/119508293/62ce48e1-3ffe-48c5-9a8c-1c48ad63f73f)

**Comment by BigyanParajuli** [comment]
![image](https://github.com/BigyanParajuli/YETIWEARS_TEAM-E/assets/119508293/0547b4b1-850e-4497-9250-b926bf09c84d)
Finally, Resolved the conflicts
