### ISSUE TITLE
Although I have stripe model it shows ModuleNotFoundError: No module named 'stripe'

### ISSUE THREAD

**Issue by Koiralapradeep** [BigyanParajuli/YETIWEARS_TEAM-E#21]
![image](https://github.com/BigyanParajuli/YETIWEARS_TEAM-E/assets/119444673/bf20802e-e650-4c5c-bc03-b8ae0a9e2ee3)
I install stripe but still i am encountering errors while making migrations

**Comment by BigyanParajuli** [comment]
Check this blog for help. If you encounter any issues again raise it further. 
Link: https://blog.finxter.com/fixed-modulenotfounderror-no-module-named-stripe/

**Comment by Koiralapradeep** [comment]
Thank you Bigyan for the link, that blog helped me.
![Screenshot 2024-05-19 225326](https://github.com/BigyanParajuli/YETIWEARS_TEAM-E/assets/119444673/3c376ee2-03c6-437c-916b-421d2fa23f31)
