### ISSUE TITLE
Problem in Viewing Promotion in My Promotions

### ISSUE THREAD

**Issue by Saugat-bit** [BigyanParajuli/YETIWEARS_TEAM-E#33]
The promotions added by the seller is not being displayed in seller dashboard my promotions section.

**Comment by Koiralapradeep** [comment]
Solved : The error was caused by fetching.

![image](https://github.com/BigyanParajuli/YETIWEARS_TEAM-E/assets/119444673/4d1fdb7b-4d2e-4f63-b270-00f594c63c38)
