### ISSUE TITLE
Problem in footer while searching for wrong items

### ISSUE THREAD

**Issue by Saugat-bit** [BigyanParajuli/YETIWEARS_TEAM-E#37]
![image (18)](https://github.com/BigyanParajuli/YETIWEARS_TEAM-E/assets/119115221/1ffeeeef-be1c-4316-9208-9666d78e2dac)
The footer comes at the top when wrong item is searched

**Comment by BigyanParajuli** [comment]
Solved 
The <body> element was set as a flex container with flex-direction: column and min-height: 100vh to ensure it fills the entire viewport height.
The main content container (<div class="max-w-4xl mx-auto py-4 px-6">) was given flex: 1 property, which allows it to grow and fill the remaining space between the header and the footer.
The footer element was given margin-top: auto property, which pushes it to the bottom when there is enough content to fill the viewport height.
![image](https://github.com/BigyanParajuli/YETIWEARS_TEAM-E/assets/119508293/11ac5e18-731f-4378-aa1b-e04da3e3c6ed)

**Comment by BigyanParajuli** [comment]
Solved: 
The <body> element was set as a flex container with flex-direction: column and min-height: 100vh to ensure it fills the entire viewport height.
The main content container (<div class="max-w-4xl mx-auto py-4 px-6">) was given flex: 1 property, which allows it to grow and fill the remaining space between the header and the footer.
The footer element was given margin-top: auto property, which pushes it to the bottom when there is enough content to fill the viewport height.
![image](https://github.com/BigyanParajuli/YETIWEARS_TEAM-E/assets/119508293/4fed873c-e1e1-4314-a3fc-c78203463ac0)
