### ISSUE TITLE
Remove button is not properly visible

### ISSUE THREAD

**Issue by Saugat-bit** [BigyanParajuli/YETIWEARS_TEAM-E#38]
![image (19)](https://github.com/BigyanParajuli/YETIWEARS_TEAM-E/assets/119115221/4f9aa0a8-4338-4d73-aa6c-21926996b35c)
Remove button is overlapping in cart

**Comment by BigyanParajuli** [comment]
Its fixed 
![image](https://github.com/BigyanParajuli/YETIWEARS_TEAM-E/assets/119508293/b8eb8df8-96fa-4d13-a831-79d60961018f)
